### ISSUE TITLE
Is there any way to make Auto-Login Links never expire regardless of the elapsed time

### ISSUE THREAD

**Issue by Amit-Biswas** [BrianHenryIE/bh-wp-autologin-urls#17]
Hi Brian,

First and foremost, thank you for developing the Autologin URLs plugin for WordPress. It has been a great tool for me so far.

However, I was hoping to inquire if there is a way to configure the plugin such that an Auto-Login Link never expires, regardless of the number of clicks or the elapsed time since its creation. I would appreciate it if you could let me know if this is possible and, if so, how to achieve it.

Thank you for your time and consideration.

Amit Biswas
CEO, AnimationVideo.co

**Comment by BrianHenryIE** [comment]
There's a filter you can use that disables deleting it after it is used, [bh_wp_autologin_urls_should_delete_code_after_use](https://github.com/BrianHenryIE/bh-wp-autologin-urls/blob/89537fb6ff6d53d959e4313eef2ad68651b3e6c1/src/api/class-api.php#L265-L274), i.e. "never expires, regardless of the number of clicks".

```
add_filter( 'bh_wp_autologin_urls_should_delete_code_after_use', '__return_false` );
```

But there's nothing intended to stop it being deleted at its expiry time. You could remove the action used by Cron before the delete job is run:

```
add_action( 'bh_wp_autologin_urls_delete_expired_codes', function() { 
  remove_all_actions( 'bh_wp_autologin_urls_delete_expired_codes' ); 
}, 0 );
```

And you could prevent the Cron job from being scheduled with WordPress's `pre_schedule_event` filter.

I don't really recommend non-expiring codes though. They'll be saved in browser caches and access logs. What's your use case?

**Comment by Amit-Biswas** [comment]
Thank you so much for providing the filter to disable deleting auto-login links after use. I appreciate the suggestion to remove the action used by Cron before the delete job is run and for preventing the Cron job from being scheduled with WordPress's pre_schedule_event filter.

In response to your question, my use case requires auto-login links that never expire, as we have a large user base that needs frequent access to our site.

That's why: I would like to provide my clients with a magic link via email that, when clicked, will automatically log them into our WordPress site using the [BH WP Autologin URLs plugin](https://wordpress.org/plugins/bh-wp-autologin-urls/). This will help me better understand their site activity and the products that they are most interested in.

Additionally, I plan to use the [Kaya Login Notification plugin](https://wordpress.org/plugins/kaya-login-notification/) to send a welcome message to clients upon their successful login. 


To achieve this, I have installed the UsersInsights plugin, which allows me to segment and track page visits and user geolocation via the [usersinsights.com plugin](https://usersinsights.com/wordpress-user-segments/). Additionally, I have given my users the option to log out via the [persistentlogin.com plugin (Active Login Features)](https://persistentlogin.com/premium/#active-login).

**I understand the potential risks of non-expiring links. To protect our site, are there any options, such as limiting the use of magic links to only users with the [WordPress role](https://wordpress.com/support/user-roles/) of "Subscriber"**

Additionally, I would like to know if it is possible to completely disable auto-login links for Administrators. This would help to enhance the overall security of our site.

Thank you again for your help.

Best regards,
Amit
CEO, AnimationVideo.co
